#
# CEDAR Constants
#

# Resource types
RESOURCE_TYPE_TEMPLATE = "template"
RESOURCE_TYPE_TEMPLATE_ELEMENT = "template-element"
RESOURCE_TYPE_TEMPLATE_FIELD = "template-field"
RESOURCE_TYPE_TEMPLATE_INSTANCE = "template-instance"

MONGODB_TEMPLATE_COLLECTION = "templates"
MONGODB_TEMPLATE_ELEMENT_COLLECTION = "template-elements"
MONGODB_TEMPLATE_FIELD_COLLECTION = "template-fields"
MONGODB_TEMPLATE_INSTANCE_COLLECTION = "template-instances"